Google sign in
Fiu-Fit/Mobile pull request #11
Opened 2023-05-07 15:32 UTC by ianshih2003

2023-05-08 00:37 UTC, Ezequiel-Schejtman requested changes

2023-05-08 00:37 UTC, Ezequiel-Schejtman commented on src/screens/login/login.tsx
> +      navigation.push('Demo');
```suggestion
      navigation.push('Workouts');
```

2023-05-08 00:37 UTC, Ezequiel-Schejtman commented on src/utils/constants.ts
> +export const API_URL = 'http://192.168.0.236:8080';
Can we leave this as is, with the deployed API URL?

2023-05-08 00:37 UTC, Ezequiel-Schejtman commented on src/screens/userProfile/userProfile.tsx
> +          Cerrar sesion
English. (See the login screen, we're using english all over the app).

2023-05-09 01:49 UTC, ianshih2003 commented on src/utils/constants.ts
> +export const API_URL = 'http://192.168.0.236:8080';
Hay que hacer environments

2023-05-09 01:49 UTC, ianshih2003 commented on src/utils/constants.ts
> +export const API_URL = 'http://192.168.0.236:8080';
https://dev.to/leon_arantes/react-native-multiple-environments-setup-schemaflavors-3l7p

Existian environments en react native

2023-05-09 01:58 UTC, merged