Feature/login_and_register_screens
Fiu-Fit/Mobile pull request #2
Opened 2023-04-10 17:24 UTC by MartinUgarte

2023-04-12 02:31 UTC, ianshih2003 requested changes
- Usar camelCase
- Consultar con @Ezequiel-Schejtman el uso de prettier y husky
- Usar https://formik.org/ para los forms, te deja agregar validadores

2023-04-12 02:31 UTC, ianshih2003 commented on src/constants/endpoints.js
> +  auth_register: 'http://localhost:8080/auth/register',
hacerlo en js y usar camelCase

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +      const response = await axios.post(ENDPOINTS.auth_login, {
Esto no esta bien, lo correcto seria establecer en los defaults de axios una url base compartida y en cada llamada al back agregarle la respectiva url que se va a agregar

(https://stackoverflow.com/questions/51794553/how-do-i-create-configuration-for-axios-for-default-request-headers-in-every-htt)

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +        password: inputs.password,
con poner inputs es suficiente

`await axios.post(/auth/login, inputs)

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +    }, 3000);
No deberiamos introducir lentitud artificialmente
el loading se deberia setear antes de hacer la pegada, el set loading false se deberia hacer despues del try y el navigation.push solo se deberia hacer si el post se hace correctamente

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +          // @ts-ignore
No agregar ts-ignore

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +          password
para que es esto

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/login/index.tsx
> +          }}
Si se le agrega un id se puede hacer un handleOnChange y handleError sin necesidad de agregarle el segundo argumento, consultar con @ManuSanchez02

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/register/index.tsx
> +const RegisterScreen = ({navigation}: {navigation: any}) => {
No usar any

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/register/index.tsx
> +  logger.info('Started Register screen!');
No es necesario loggear esto

2023-04-12 02:31 UTC, ianshih2003 commented on src/screens/register/index.tsx
> +    role: 'Trainer',
Usar un enum, preferible el que esta en common, si no esta agregarlo

2023-04-17 16:40 UTC, MartinUgarte commented on src/screens/login/index.tsx
> +          password
Si es true, se pone el ojo de ocultar contraseña en el input

2023-04-18 00:45 UTC, merged